# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46788253af6bceeebd6f1f3ffa615efbebc3d7a2de0cd9efac47f280f703fbe4fda68feb46c16d1e11d1e33a0975a01689367cabd4a2cbb13cd7eb9fb9304dda

test:
  secret_key_base: e78e3cb1837c881c58c3d296e7f7785f550ed2f14c9f1a2a9004bfc0bf3b7ab3e93b73f37899b54ef20300e4dad921d618361b85e3f154cda164d16ebf83ad8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
